openapi: 3.0.3
info:
  title: 'Poligon API'
  version: 0.1.0
  description: This is Poligon API Description
  contact: {
    name: Yakub Jorayev,
    email: jorayev2494@gmail.com,
    url: https://github.com/jorayev2494
  }
servers:
  - {
      description: 'localhost',
      url: 'http://127.0.0.1:8088/api/'
  }

tags: null
paths:
  /users:
    description: Get Users
    get:
      summary: Get Users
      tags:
        - Users

      responses:
        200:
          description: "User Resource"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResource'



components:
  schemas:
    UserResource:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "Linda Cronin Sr."
        email:
          type: string
          example: "test@gmail.com"
        email_verified_at:
          type: string
          example: "17 hours ago"
        created_at:
          type: string
          example: "17 hours ago"
        updated_at:
          type: string
          example: "17 hours ago"

  responses: null
  headers: null
  parameters: null
  links: null
  examples: null
