openapi: 3.0.3

info:
  title: 'Poligon API'
  version: 0.1.0
  description: This is Poligon API Description
  contact: {
    name: Yakub Jorayev,
    email: jorayev2494@gmail.com,
    url: https://github.com/jorayev2494
  }

servers:
  - {
      description: 'localhost',
      url: 'http://127.0.0.1:8088/api/'
  }

tags: null

paths:
  /users:
    description: Get Users
    get:
      summary: Get Users
      tags:
        - Public Users

      responses:
        200:
          description: "User Resource"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserResource'

  /users/{user_id}:
    get:
      summary: "Show User"
      tags:
        - Public Users

      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
            example: 3

      responses:
        200:
          description: "Show User"
          content:
            application/jsom:
              schema:
                $ref: '#/components/schemas/UserResource'

    put:
      summary: Update User
      tags:
        - Public Users

      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
            example: 3

        - name: name
          in: query
          required: false
          schema:
            type: string
            example: "UserName"

        - name: email
          in: query
          required: false
          schema:
            type: string
            example: "user@gmail.com"

      responses:
        202:
          description: Accepted Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResource'

    delete:
      summary: Delete User
      tags:
        - Public Users

      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
            example: 3

      responses:
        204:
          description: No Content

components:
  schemas:
    UserResource:
      type: object
      properties:
        id:
          type: integer
          example: 1
        first_name:
          type: string
          example: "Linda"
        last_name:
          type: string
          example: "Cronin"
        email:
          type: string
          example: "test@gmail.com"
        phone:
          type: string
          example: "+38095123456"
        email_verified_at:
          type: string
          example: "17 hours ago"
        created_at:
          type: string
          example: "17 hours ago"
        updated_at:
          type: string
          example: "17 hours ago"

  responses: null
  headers: null
  parameters: null
  links: null
  examples: null
